#!/usr/bin/env bash

JAVACMD=${JAVACMD:=./graalvm/bin/java}

PROGRAM_ARGS=""
JAVA_ARGS=""
verbose=0

for opt in "$@"
do
  case $opt in
    -debug)
      JAVA_ARGS="$JAVA_ARGS -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=y" ;;
    -dump)
      JAVA_ARGS="$JAVA_ARGS -Dgraal.Dump= -Dgraal.MethodFilter=Truffle.* -Dgraal.TruffleBackgroundCompilation=false -Dgraal.TraceTruffleCompilation=true -Dgraal.TraceTruffleCompilationDetails=true" ;;
    -disassemble)
      JAVA_ARGS="$JAVA_ARGS -XX:CompileCommand=print,*OptimizedCallTarget.callRoot -XX:CompileCommand=exclude,*OptimizedCallTarget.callRoot -Dgraal.TruffleBackgroundCompilation=false -Dgraal.TraceTruffleCompilation=true -Dgraal.TraceTruffleCompilationDetails=true" ;;
    -J*)
      opt=${opt:2}
      JAVA_ARGS="$JAVA_ARGS $opt" ;;
    -go)
      verbose=1 ;;
    *)
      PROGRAM_ARGS="$PROGRAM_ARGS $opt" ;;
  esac
done

TRUFFLE_LIB=./graalvm/jre/lib/truffle

if [ $verbose -eq 1 ]; then
    TruffleOutput="${PROGRAM_ARGS}.Truffle.output"
    GoOutput="${PROGRAM_ARGS}.Go.output"
    DIRO="TestOutputs/"
    echo "Truffle Output:"
    $JAVACMD $JAVA_ARGS -XX:-UseJVMCIClassLoader -Xbootclasspath/a:$TRUFFLE_LIB/truffle-api.jar:$TRUFFLE_LIB/locator.jar:$TRUFFLE_LIB/truffle-nfi.jar -cp ./target/classes com.oracle.app.GoMain $PROGRAM_ARGS | tee "$DIRO""${TruffleOutput}"
    
    go run $PROGRAM_ARGS &>"$DIRO""${GoOutput}"
    echo "Go Output:"
    cat "$DIRO""${GoOutput}"
    echo "Any diff listed below:"
    diff "$DIRO""${GoOutput}" "$DIRO""${TruffleOutput}"
    rm -f *.ast
else
    $JAVACMD $JAVA_ARGS -XX:-UseJVMCIClassLoader -Xbootclasspath/a:$TRUFFLE_LIB/truffle-api.jar:$TRUFFLE_LIB/locator.jar:$TRUFFLE_LIB/truffle-nfi.jar -cp ./target/classes com.oracle.app.GoMain $PROGRAM_ARGS
fi
    #rm -f *.ast
